spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: dev_user
    password: password
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: mysql
# Generates SQL schema for MySQL in root folder of the project with name 'recipe_database_init.sql'
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: recipe_database_init.sql

