spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe-prod
    username: prod_user
    password: password
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
